/** This file is auto-generated by icon-convert script. Do not modify directly as changes may be overwritten. */

type ArcheryProps = {
  className?: string;
};

export default function Archery({ className }: ArcheryProps) {
  return (
    <svg
      className={className}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M8 12H17M8 12L6 10H2L4 12L2 14H6L8 12ZM17 12L15 10M17 12L15 14M16 22.5C18.761 22.5 21 17.799 21 12C21 6.201 18.761 1.5 16 1.5C13.239 1.5 11 6.201 11 12C11 17.799 13.239 22.5 16 22.5Z"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      ></path>
    </svg>
  );
}
