/** This file is auto-generated by icon-convert script. Do not modify directly as changes may be overwritten. */

type ArrowRightProps = {
  className?: string;
};

export default function ArrowRight({ className }: Readonly<ArrowRightProps>) {
  return (
    <svg
      className={className}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M3 12H21M21 12L12.5 3.5M21 12L12.5 20.5"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      ></path>
    </svg>
  );
}
