/** This file is auto-generated by icon-convert script. Do not modify directly as changes may be overwritten. */

type CheckProps = {
  className?: string;
};

export default function Check({ className }: Readonly<CheckProps>) {
  return (
    <svg
      className={className}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M5 13L9 17L19 7"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      ></path>
    </svg>
  );
}
