/** This file is auto-generated by icon-convert script. Do not modify directly as changes may be overwritten. */

type CollectbookProps = {
  className?: string;
};

export default function Collectbook({ className }: Readonly<CollectbookProps>) {
  return (
    <svg
      className={className}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M4 19V5C4 4.46957 4.21071 3.96086 4.58579 3.58579C4.96086 3.21071 5.46957 3 6 3H19.4C19.5591 3 19.7117 3.06321 19.8243 3.17574C19.9368 3.28826 20 3.44087 20 3.6V16.714"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
      ></path>
      <path
        d="M10 14C10 14 10.9 10.882 13 9"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      ></path>
      <path
        d="M12.802 12.425L12.668 12.437C11.8543 12.5129 11.0437 12.2638 10.413 11.744C9.7824 11.2243 9.38299 10.4762 9.302 9.66303C9.26202 9.26154 9.30184 8.85611 9.41916 8.47007C9.53647 8.08403 9.72898 7.725 9.98559 7.41365C10.2422 7.10229 10.5579 6.84476 10.9144 6.65587C11.2709 6.46698 11.6613 6.35047 12.063 6.31303L15.049 6.03303C15.1411 6.02438 15.2329 6.05256 15.3043 6.1114C15.3757 6.17024 15.4209 6.25496 15.43 6.34703L15.685 8.92703C15.7269 9.34628 15.6854 9.76969 15.563 10.1728C15.4406 10.576 15.2396 10.951 14.9716 11.2761C14.7036 11.6012 14.3739 11.8702 14.0016 12.0673C13.6292 12.2645 13.2215 12.3861 12.802 12.425Z"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      ></path>
      <path
        d="M6 17H20M6 21H20"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
      ></path>
      <path
        d="M6 21C5.46957 21 4.96086 20.7893 4.58579 20.4142C4.21071 20.0391 4 19.5304 4 19C4 18.4696 4.21071 17.9609 4.58579 17.5858C4.96086 17.2107 5.46957 17 6 17"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      ></path>
    </svg>
  );
}
