/** This file is auto-generated by icon-convert script. Do not modify directly as changes may be overwritten. */

type EditProps = {
  className?: string;
};

export default function Edit({ className }: Readonly<EditProps>) {
  return (
    <svg
      className={className}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M14.363 5.65201L15.843 4.17201C16.0287 3.98621 16.2492 3.83882 16.492 3.73826C16.7347 3.6377 16.9948 3.58594 17.2575 3.58594C17.5202 3.58594 17.7804 3.6377 18.0231 3.73826C18.2658 3.83882 18.4863 3.98621 18.672 4.17201L20.086 5.58601C20.461 5.96107 20.6716 6.46968 20.6716 7.00001C20.6716 7.53034 20.461 8.03895 20.086 8.41401L18.606 9.89401M14.363 5.65201L4.74701 15.267C4.41499 15.599 4.21038 16.0373 4.16901 16.505L3.92701 19.245C3.91401 19.3907 3.93312 19.5374 3.98298 19.6749C4.03285 19.8123 4.11226 19.9372 4.21562 20.0407C4.31897 20.1441 4.44376 20.2236 4.58119 20.2736C4.71862 20.3236 4.86534 20.3429 5.01101 20.33L7.75101 20.088C8.21943 20.0471 8.65847 19.8425 8.99101 19.51L18.606 9.89401M14.363 5.65201L18.606 9.89401"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      ></path>
    </svg>
  );
}
