/** This file is auto-generated by icon-convert script. Do not modify directly as changes may be overwritten. */

type ExploreProps = {
  className?: string;
};

export default function Explore({ className }: ExploreProps) {
  return (
    <svg
      className={className}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M21.5 14L20 9C20 9 19.5 7 17.5 7C17.5 7 17.5 5 15.5 5C13.5 5 13.5 7 13.5 7H10.5C10.5 7 10.5 5 8.5 5C6.5 5 6.5 7 6.5 7C4.5 7 4 9 4 9L2.5 14"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      ></path>
      <path
        d="M6 20C7.06087 20 8.07828 19.5786 8.82843 18.8284C9.57857 18.0783 10 17.0609 10 16C10 14.9391 9.57857 13.9217 8.82843 13.1716C8.07828 12.4214 7.06087 12 6 12C4.93913 12 3.92172 12.4214 3.17157 13.1716C2.42143 13.9217 2 14.9391 2 16C2 17.0609 2.42143 18.0783 3.17157 18.8284C3.92172 19.5786 4.93913 20 6 20ZM18 20C19.0609 20 20.0783 19.5786 20.8284 18.8284C21.5786 18.0783 22 17.0609 22 16C22 14.9391 21.5786 13.9217 20.8284 13.1716C20.0783 12.4214 19.0609 12 18 12C16.9391 12 15.9217 12.4214 15.1716 13.1716C14.4214 13.9217 14 14.9391 14 16C14 17.0609 14.4214 18.0783 15.1716 18.8284C15.9217 19.5786 16.9391 20 18 20Z"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      ></path>
      <path
        d="M12 16C12.5304 16 13.0391 15.7893 13.4142 15.4142C13.7893 15.0391 14 14.5304 14 14C14 13.4696 13.7893 12.9609 13.4142 12.5858C13.0391 12.2107 12.5304 12 12 12C11.4696 12 10.9609 12.2107 10.5858 12.5858C10.2107 12.9609 10 13.4696 10 14C10 14.5304 10.2107 15.0391 10.5858 15.4142C10.9609 15.7893 11.4696 16 12 16Z"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      ></path>
    </svg>
  );
}
