/** This file is auto-generated by icon-convert script. Do not modify directly as changes may be overwritten. */

type HostProps = {
  className?: string;
};

export default function Host({ className }: Readonly<HostProps>) {
  return (
    <svg
      className={className}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M19.2 17L21 7L14.7 10L12 7L9.3 10L3 7L4.8 17H19.2Z"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      ></path>
    </svg>
  );
}
