/** This file is auto-generated by icon-convert script. Do not modify directly as changes may be overwritten. */

type MoveProps = {
  className?: string;
};

export default function Move({ className }: Readonly<MoveProps>) {
  return (
    <svg
      className={className}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M8.34804 12.157H2M2 12.157L4.53921 14.6962M2 12.157L4.53921 9.61777"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      ></path>
      <path
        d="M12.1569 8.34809V2.00005M12.1569 2.00005L14.6961 4.53927M12.1569 2.00005L9.61765 4.53927"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      ></path>
      <path
        d="M12.1569 15.9659V22.3139M12.1569 22.3139L9.61765 19.7747M12.1569 22.3139L14.6961 19.7747"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      ></path>
      <path
        d="M15.9657 12.157H22.3137M22.3137 12.157L19.7745 9.61777M22.3137 12.157L19.7745 14.6962"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      ></path>
    </svg>
  );
}
