/** This file is auto-generated by icon-convert script. Do not modify directly as changes may be overwritten. */

type NavArrowDownProps = {
  className?: string;
};

export default function NavArrowDown({
  className,
}: Readonly<NavArrowDownProps>) {
  return (
    <svg
      className={className}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M6 9L12 15L18 9"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      ></path>
    </svg>
  );
}
