/** This file is auto-generated by icon-convert script. Do not modify directly as changes may be overwritten. */

type NavArrowRightProps = {
  className?: string;
};

export default function NavArrowRight({
  className,
}: Readonly<NavArrowRightProps>) {
  return (
    <svg
      className={className}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M9 6L15 12L9 18"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      ></path>
    </svg>
  );
}
