/** This file is auto-generated by icon-convert script. Do not modify directly as changes may be overwritten. */

type PlusProps = {
  className?: string;
};

export default function Plus({ className }: Readonly<PlusProps>) {
  return (
    <svg
      className={className}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M6 12H12M12 12H18M12 12V6M12 12V18"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      ></path>
    </svg>
  );
}
