/** This file is auto-generated by icon-convert script. Do not modify directly as changes may be overwritten. */

type SentProps = {
  className?: string;
};

export default function Sent({ className }: SentProps) {
  return (
    <svg
      className={className}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M22 12L3 20L6.563 12L3 4L22 12ZM22 12H6.5"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      ></path>
    </svg>
  );
}
