/** This file is auto-generated by icon-convert script. Do not modify directly as changes may be overwritten. */

type UserProps = {
  className?: string;
};

export default function User({ className }: Readonly<UserProps>) {
  return (
    <svg
      className={className}
      viewBox="0 0 206 64"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <g filter="url(#filter0_dddddd_1411_536)">
        <path
          d="M96 40V39C96 35.134 99.134 32 103 32C106.866 32 110 35.134 110 39V40"
          stroke="white"
          strokeWidth="1.5"
          strokeLinecap="round"
          strokeLinejoin="round"
        ></path>
        <path
          d="M103 32C105.209 32 107 30.2091 107 28C107 25.7909 105.209 24 103 24C100.791 24 99 25.7909 99 28C99 30.2091 100.791 32 103 32Z"
          stroke="white"
          strokeWidth="1.5"
          strokeLinecap="round"
          strokeLinejoin="round"
        ></path>
      </g>
      <defs>
        <filter
          id="filter0_dddddd_1411_536"
          x="0.279999"
          y="-70.72"
          width="205.44"
          height="205.44"
          filterUnits="userSpaceOnUse"
          colorInterpolationFilters="sRGB"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feColorMatrix
            in="SourceAlpha"
            type="matrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
            result="hardAlpha"
          ></feColorMatrix>
          <feOffset></feOffset>
          <feGaussianBlur stdDeviation="1.08"></feGaussianBlur>
          <feColorMatrix
            type="matrix"
            values="0 0 0 0 0.705882 0 0 0 0 0.905882 0 0 0 0 0.882353 0 0 0 1 0"
          ></feColorMatrix>
          <feBlend
            mode="normal"
            in2="BackgroundImageFix"
            result="effect1_dropShadow_1411_536"
          ></feBlend>
          <feColorMatrix
            in="SourceAlpha"
            type="matrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
            result="hardAlpha"
          ></feColorMatrix>
          <feOffset></feOffset>
          <feGaussianBlur stdDeviation="2.16"></feGaussianBlur>
          <feColorMatrix
            type="matrix"
            values="0 0 0 0 0.705882 0 0 0 0 0.905882 0 0 0 0 0.882353 0 0 0 1 0"
          ></feColorMatrix>
          <feBlend
            mode="normal"
            in2="effect1_dropShadow_1411_536"
            result="effect2_dropShadow_1411_536"
          ></feBlend>
          <feColorMatrix
            in="SourceAlpha"
            type="matrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
            result="hardAlpha"
          ></feColorMatrix>
          <feOffset></feOffset>
          <feGaussianBlur stdDeviation="7.56"></feGaussianBlur>
          <feColorMatrix
            type="matrix"
            values="0 0 0 0 0.705882 0 0 0 0 0.905882 0 0 0 0 0.882353 0 0 0 1 0"
          ></feColorMatrix>
          <feBlend
            mode="normal"
            in2="effect2_dropShadow_1411_536"
            result="effect3_dropShadow_1411_536"
          ></feBlend>
          <feColorMatrix
            in="SourceAlpha"
            type="matrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
            result="hardAlpha"
          ></feColorMatrix>
          <feOffset></feOffset>
          <feGaussianBlur stdDeviation="15.12"></feGaussianBlur>
          <feColorMatrix
            type="matrix"
            values="0 0 0 0 0.705882 0 0 0 0 0.905882 0 0 0 0 0.882353 0 0 0 1 0"
          ></feColorMatrix>
          <feBlend
            mode="normal"
            in2="effect3_dropShadow_1411_536"
            result="effect4_dropShadow_1411_536"
          ></feBlend>
          <feColorMatrix
            in="SourceAlpha"
            type="matrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
            result="hardAlpha"
          ></feColorMatrix>
          <feOffset></feOffset>
          <feGaussianBlur stdDeviation="25.92"></feGaussianBlur>
          <feColorMatrix
            type="matrix"
            values="0 0 0 0 0.705882 0 0 0 0 0.905882 0 0 0 0 0.882353 0 0 0 1 0"
          ></feColorMatrix>
          <feBlend
            mode="normal"
            in2="effect4_dropShadow_1411_536"
            result="effect5_dropShadow_1411_536"
          ></feBlend>
          <feColorMatrix
            in="SourceAlpha"
            type="matrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
            result="hardAlpha"
          ></feColorMatrix>
          <feOffset></feOffset>
          <feGaussianBlur stdDeviation="45.36"></feGaussianBlur>
          <feColorMatrix
            type="matrix"
            values="0 0 0 0 0.705882 0 0 0 0 0.905882 0 0 0 0 0.882353 0 0 0 1 0"
          ></feColorMatrix>
          <feBlend
            mode="normal"
            in2="effect5_dropShadow_1411_536"
            result="effect6_dropShadow_1411_536"
          ></feBlend>
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="effect6_dropShadow_1411_536"
            result="shape"
          ></feBlend>
        </filter>
      </defs>
    </svg>
  );
}
