/** This file is auto-generated by icon-convert script. Do not modify directly as changes may be overwritten. */

type XProps = {
  className?: string;
};

export default function X({ className }: Readonly<XProps>) {
  return (
    <svg
      className={className}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M6.75827 17.2426L12.0009 12M12.0009 12L17.2435 6.75736M12.0009 12L6.75827 6.75736M12.0009 12L17.2435 17.2426"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      ></path>
    </svg>
  );
}
