/** This file is auto-generated by icon-convert script. Do not modify directly as changes may be overwritten. */

type ArrowLeftProps = {
  className?: string;
};

export default function ArrowLeft({ className }: ArrowLeftProps) {
  return (
    <svg
      className={className}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M21 12H3M3 12L11.5 3.5M3 12L11.5 20.5"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      ></path>
    </svg>
  );
}
