/** This file is auto-generated by icon-convert script. Do not modify directly as changes may be overwritten. */

type LongArrowUpLeftProps = {
  className?: string;
};

export default function LongArrowUpLeft({ className }: LongArrowUpLeftProps) {
  return (
    <svg
      className={className}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M10.25 4.75L6.75 8.25L10.25 11.75"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      ></path>
      <path
        d="M6.75 8.25H12.75C14.9591 8.25 16.75 10.0409 16.75 12.25V19.25"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      ></path>
    </svg>
  );
}
