/** This file is auto-generated by icon-convert script. Do not modify directly as changes may be overwritten. */

type ReportQuestionProps = {
  className?: string;
};

export default function ReportQuestion({ className }: ReportQuestionProps) {
  return (
    <svg
      className={className}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M3 21H12H21"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      ></path>
      <path
        d="M12.2218 5.82837L15.0503 2.99994L20 7.94969L17.1716 10.7781M12.2218 5.82837L6.61522 11.435C6.42769 11.6225 6.32233 11.8769 6.32233 12.1421V16.6776H10.8579C11.1231 16.6776 11.3774 16.5723 11.565 16.3847L17.1716 10.7781M12.2218 5.82837L17.1716 10.7781"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      ></path>
    </svg>
  );
}
