/** This file is auto-generated by icon-convert script. Do not modify directly as changes may be overwritten. */

type ShowChatProps = {
  className?: string;
};

export default function ShowChat({ className }: ShowChatProps) {
  return (
    <svg
      className={className}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M15 3H9H3.6C3.26863 3 3 3.26863 3 3.6V20.4C3 20.7314 3.26863 21 3.6 21H9H15M15 3H20.4C20.7314 3 21 3.26863 21 3.6V20.4C21 20.7314 20.7314 21 20.4 21H15M15 3V21"
        stroke="currentColor"
        strokeWidth="1.5"
      ></path>
    </svg>
  );
}
