/** This file is auto-generated by icon-convert script. Do not modify directly as changes may be overwritten. */
export { default as Arcade } from "./generate/arcade";
export { default as Archery } from "./generate/archery";
export { default as ArrowLeft } from "./generate/arrow-left";
export { default as ArrowRight } from "./generate/arrow-right";
export { default as Badge } from "./generate/badge";
export { default as BrightCrown } from "./generate/bright-crown";
export { default as Calendar } from "./generate/calendar";
export { default as Chat } from "./generate/chat";
export { default as Check } from "./generate/check";
export { default as ChessRook } from "./generate/chess-rook";
export { default as Clock } from "./generate/clock";
export { default as Collectbook } from "./generate/collectbook";
export { default as Discord } from "./generate/discord";
export { default as EditMode } from "./generate/edit-mode";
export { default as Edit } from "./generate/edit";
export { default as Explore } from "./generate/explore";
export { default as FullScreen } from "./generate/full-screen";
export { default as Gamepad } from "./generate/gamepad";
export { default as Github } from "./generate/github";
export { default as Google } from "./generate/google";
export { default as Heart } from "./generate/heart";
export { default as HelpCircle } from "./generate/help-circle";
export { default as Home } from "./generate/home";
export { default as Host } from "./generate/host";
export { default as HotAirBalloon } from "./generate/hot-air-balloon";
export { default as HouseLock } from "./generate/house-lock";
export { default as House } from "./generate/house";
export { default as LeaveGame } from "./generate/leave-game";
export { default as Linkedin } from "./generate/linkedin";
export { default as LogOut } from "./generate/log-out";
export { default as Logo } from "./generate/logo";
export { default as LongArrowUpLeft } from "./generate/long-arrow-up-left";
export { default as Menu } from "./generate/menu";
export { default as Move } from "./generate/move";
export { default as NavArrowDown } from "./generate/nav-arrow-down";
export { default as NavArrowLeft } from "./generate/nav-arrow-left";
export { default as NavArrowRight } from "./generate/nav-arrow-right";
export { default as Nonpublic } from "./generate/nonpublic";
export { default as Notification } from "./generate/notification";
export { default as Play } from "./generate/play";
export { default as Player } from "./generate/player";
export { default as Plus } from "./generate/plus";
export { default as Preview } from "./generate/preview";
export { default as Refresh } from "./generate/refresh";
export { default as ReportQuestion } from "./generate/report-question";
export { default as Search } from "./generate/search";
export { default as Sent } from "./generate/sent";
export { default as Sharing } from "./generate/sharing";
export { default as ShowChat } from "./generate/show-chat";
export { default as ShowUi } from "./generate/show-ui";
export { default as Sort } from "./generate/sort";
export { default as Spiral } from "./generate/spiral";
export { default as Star } from "./generate/star";
export { default as Upload } from "./generate/upload";
export { default as User } from "./generate/user";
export { default as User_host } from "./generate/user_host";
export { default as X } from "./generate/x";
export type IconName =
  | "Arcade"
  | "Archery"
  | "ArrowLeft"
  | "ArrowRight"
  | "Badge"
  | "BrightCrown"
  | "Calendar"
  | "Chat"
  | "Check"
  | "ChessRook"
  | "Clock"
  | "Collectbook"
  | "Discord"
  | "EditMode"
  | "Edit"
  | "Explore"
  | "FullScreen"
  | "Gamepad"
  | "Github"
  | "Google"
  | "Heart"
  | "HelpCircle"
  | "Home"
  | "Host"
  | "HotAirBalloon"
  | "HouseLock"
  | "House"
  | "LeaveGame"
  | "Linkedin"
  | "LogOut"
  | "Logo"
  | "LongArrowUpLeft"
  | "Menu"
  | "Move"
  | "NavArrowDown"
  | "NavArrowLeft"
  | "NavArrowRight"
  | "Nonpublic"
  | "Notification"
  | "Play"
  | "Player"
  | "Plus"
  | "Preview"
  | "Refresh"
  | "ReportQuestion"
  | "Search"
  | "Sent"
  | "Sharing"
  | "ShowChat"
  | "ShowUi"
  | "Sort"
  | "Spiral"
  | "Star"
  | "Upload"
  | "User"
  | "User_host"
  | "X";
