import fs from "fs";
import path from "path";

const rootDir = path.join(__dirname, "../../");
const iconsDir = path.join(rootDir, "/components/shared/Icon/icons/generate");
const exportFile = path.join(rootDir, "/components/shared/Icon/icons/index.ts");

(async () => {
  const files = await fs.promises.readdir(iconsDir);
  const iconComponents = files.filter((file) => file.endsWith(".tsx"));

  const exportNames: string[] = [];
  let exportString =
    "/** This file is auto-generated by icon-convert script. Do not modify directly as changes may be overwritten. */\n";

  iconComponents.forEach((component) => {
    const fileName = component.split(".")[0];
    const upperCaseFileName = fileName
      .replace(/-([a-z])/g, (_, letter) => letter.toUpperCase())
      .replace(/^[a-z]/, (match) => match.toUpperCase());
    exportString += `export { default as ${upperCaseFileName} } from "./generate/${fileName}";\n`;
    exportNames.push(`"${upperCaseFileName}"`);
  });

  exportString += `export type IconName = ${exportNames.join(" | ")}\n`;

  await fs.promises.writeFile(exportFile, exportString, "utf-8");
})();
